use std::sync::Arc;

use crate::AppState;
use crate::models::TrackedIssue;
use super::analyzer::GeneratedFix;

/// Create a GitHub PR with the generated fix
pub async fn create_fix_pr(
    state: &Arc<AppState>,
    issue: &TrackedIssue,
    fix: &GeneratedFix,
) -> Result<String, String> {
    let token = &state.config.github_token;

    // Parse owner/repo
    let parts: Vec<&str> = issue.repo.split('/').collect();
    if parts.len() != 2 {
        return Err(format!("Invalid repo format: {}", issue.repo));
    }
    let (owner, repo) = (parts[0], parts[1]);

    // Step 1: Get default branch SHA
    let default_branch = get_default_branch(&state.http, token, owner, repo).await?;
    let base_sha = get_branch_sha(&state.http, token, owner, repo, &default_branch).await?;

    // Step 2: Create branch
    create_branch(&state.http, token, owner, repo, &fix.branch_name, &base_sha).await?;
    tracing::info!("📌 Branch created: {}", fix.branch_name);

    // Step 3: Push file changes
    for change in &fix.file_changes {
        push_file(&state.http, token, owner, repo, &fix.branch_name, &change.path, &change.content, &fix.commit_message).await?;
    }
    tracing::info!("📝 {} files pushed", fix.file_changes.len());

    // Step 4: Create PR
    let pr_title = format!("[Muninn Auto-Fix] {}", issue.title);
    let pr_body = format!(
        "## 🐦 Muninn Auto-Fix\n\n**Issue:** #{}\n**Root cause:** AI-analyzed\n\n### Changes\n{}\n\n---\n*This PR was automatically generated by Muninn. Please review carefully before merging.*",
        issue.issue_number,
        fix.file_changes.iter().map(|f| format!("- `{}`", f.path)).collect::<Vec<_>>().join("\n"),
    );

    let pr_url = create_pull_request(
        &state.http, token, owner, repo,
        &pr_title, &pr_body,
        &fix.branch_name, &default_branch,
    ).await?;

    Ok(pr_url)
}

async fn get_default_branch(http: &reqwest::Client, token: &str, owner: &str, repo: &str) -> Result<String, String> {
    let url = format!("https://api.github.com/repos/{}/{}", owner, repo);
    let resp = github_get(http, token, &url).await?;
    resp.get("default_branch")
        .and_then(|b| b.as_str())
        .map(String::from)
        .ok_or_else(|| "Could not get default branch".to_string())
}

async fn get_branch_sha(http: &reqwest::Client, token: &str, owner: &str, repo: &str, branch: &str) -> Result<String, String> {
    let url = format!("https://api.github.com/repos/{}/{}/git/ref/heads/{}", owner, repo, branch);
    let resp = github_get(http, token, &url).await?;
    resp.pointer("/object/sha")
        .and_then(|s| s.as_str())
        .map(String::from)
        .ok_or_else(|| "Could not get branch SHA".to_string())
}

async fn create_branch(http: &reqwest::Client, token: &str, owner: &str, repo: &str, branch: &str, sha: &str) -> Result<(), String> {
    let url = format!("https://api.github.com/repos/{}/{}/git/refs", owner, repo);
    let body = serde_json::json!({
        "ref": format!("refs/heads/{}", branch),
        "sha": sha,
    });
    github_post(http, token, &url, &body).await?;
    Ok(())
}

async fn push_file(http: &reqwest::Client, token: &str, owner: &str, repo: &str, branch: &str, path: &str, content: &str, message: &str) -> Result<(), String> {
    let url = format!("https://api.github.com/repos/{}/{}/contents/{}", owner, repo, path);

    // Check if file exists (to get SHA for update)
    let existing_sha = match github_get(http, token, &format!("{}?ref={}", url, branch)).await {
        Ok(resp) => resp.get("sha").and_then(|s| s.as_str()).map(String::from),
        Err(_) => None,
    };

    let encoded = base64_encode(content);
    let mut body = serde_json::json!({
        "message": message,
        "content": encoded,
        "branch": branch,
    });
    if let Some(sha) = existing_sha {
        body["sha"] = serde_json::Value::String(sha);
    }

    github_put(http, token, &url, &body).await?;
    Ok(())
}

async fn create_pull_request(http: &reqwest::Client, token: &str, owner: &str, repo: &str, title: &str, body: &str, head: &str, base: &str) -> Result<String, String> {
    let url = format!("https://api.github.com/repos/{}/{}/pulls", owner, repo);
    let payload = serde_json::json!({
        "title": title,
        "body": body,
        "head": head,
        "base": base,
        "draft": true,
    });
    let resp = github_post(http, token, &url, &payload).await?;
    resp.get("html_url")
        .and_then(|u| u.as_str())
        .map(String::from)
        .ok_or_else(|| "Could not get PR URL".to_string())
}

// ── GitHub API helpers ──

async fn github_get(http: &reqwest::Client, token: &str, url: &str) -> Result<serde_json::Value, String> {
    let resp = http.get(url)
        .header("Accept", "application/vnd.github+json")
        .header("Authorization", format!("Bearer {}", token))
        .header("User-Agent", "Muninn/0.1.0")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .send().await
        .map_err(|e| format!("GitHub GET failed: {}", e))?;
    if !resp.status().is_success() {
        return Err(format!("GitHub GET {} returned {}", url, resp.status()));
    }
    resp.json().await.map_err(|e| format!("JSON parse error: {}", e))
}

async fn github_post(http: &reqwest::Client, token: &str, url: &str, body: &serde_json::Value) -> Result<serde_json::Value, String> {
    let resp = http.post(url)
        .header("Accept", "application/vnd.github+json")
        .header("Authorization", format!("Bearer {}", token))
        .header("User-Agent", "Muninn/0.1.0")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .json(body)
        .send().await
        .map_err(|e| format!("GitHub POST failed: {}", e))?;
    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(format!("GitHub POST {} returned {}: {}", url, status, body));
    }
    resp.json().await.map_err(|e| format!("JSON parse error: {}", e))
}

async fn github_put(http: &reqwest::Client, token: &str, url: &str, body: &serde_json::Value) -> Result<serde_json::Value, String> {
    let resp = http.put(url)
        .header("Accept", "application/vnd.github+json")
        .header("Authorization", format!("Bearer {}", token))
        .header("User-Agent", "Muninn/0.1.0")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .json(body)
        .send().await
        .map_err(|e| format!("GitHub PUT failed: {}", e))?;
    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(format!("GitHub PUT {} returned {}: {}", url, status, body));
    }
    resp.json().await.map_err(|e| format!("JSON parse error: {}", e))
}

fn base64_encode(content: &str) -> String {
    use std::io::Write;
    let mut buf = Vec::new();
    {
        let mut encoder = Base64Encoder::new(&mut buf);
        encoder.write_all(content.as_bytes()).unwrap();
        encoder.finish().unwrap();
    }
    String::from_utf8(buf).unwrap()
}

/// Simple base64 encoder (avoiding extra dependency)
struct Base64Encoder<'a> {
    output: &'a mut Vec<u8>,
    buffer: Vec<u8>,
}

impl<'a> Base64Encoder<'a> {
    fn new(output: &'a mut Vec<u8>) -> Self {
        Self { output, buffer: Vec::new() }
    }

    fn finish(mut self) -> std::io::Result<()> {
        self.flush_buffer();
        Ok(())
    }

    fn flush_buffer(&mut self) {
        const CHARS: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        let mut i = 0;
        while i + 3 <= self.buffer.len() {
            let b0 = self.buffer[i] as usize;
            let b1 = self.buffer[i + 1] as usize;
            let b2 = self.buffer[i + 2] as usize;
            self.output.push(CHARS[b0 >> 2]);
            self.output.push(CHARS[((b0 & 0x03) << 4) | (b1 >> 4)]);
            self.output.push(CHARS[((b1 & 0x0f) << 2) | (b2 >> 6)]);
            self.output.push(CHARS[b2 & 0x3f]);
            i += 3;
        }
        let remaining = self.buffer.len() - i;
        if remaining == 1 {
            let b0 = self.buffer[i] as usize;
            self.output.push(CHARS[b0 >> 2]);
            self.output.push(CHARS[(b0 & 0x03) << 4]);
            self.output.push(b'=');
            self.output.push(b'=');
        } else if remaining == 2 {
            let b0 = self.buffer[i] as usize;
            let b1 = self.buffer[i + 1] as usize;
            self.output.push(CHARS[b0 >> 2]);
            self.output.push(CHARS[((b0 & 0x03) << 4) | (b1 >> 4)]);
            self.output.push(CHARS[(b1 & 0x0f) << 2]);
            self.output.push(b'=');
        }
        self.buffer.clear();
    }
}

impl<'a> std::io::Write for Base64Encoder<'a> {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.buffer.extend_from_slice(buf);
        Ok(buf.len())
    }
    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_base64_encode() {
        assert_eq!(base64_encode("Hello, World!"), "SGVsbG8sIFdvcmxkIQ==");
        assert_eq!(base64_encode("abc"), "YWJj");
        assert_eq!(base64_encode(""), "");
    }

    #[test]
    fn test_repo_parse() {
        let repo = "MegaWiz-Dev-Team/Mimir";
        let parts: Vec<&str> = repo.split('/').collect();
        assert_eq!(parts.len(), 2);
        assert_eq!(parts[0], "MegaWiz-Dev-Team");
        assert_eq!(parts[1], "Mimir");
    }
}
